# Build Station: full Lineage common product config required for OTA install tools
$(call inherit-product, vendor/lineage/config/common_full_phone.mk)

# Auto-generated by Build Station ROM adaptation.
# Keeps donor makefile intact and exposes the target lunch product.
$(call inherit-product, $(LOCAL_PATH)/cm.mk)

PRODUCT_NAME := cm_M6T
PRODUCT_DEVICE := M6T
PRODUCT_BRAND := meizu
PRODUCT_MODEL := M6T

# Build Station: hard-stop emulator/goldfish inheritance in clean M6 builds.
PRODUCT_CHARACTERISTICS := phone
PRODUCT_PACKAGES := $(filter-out \
    audio.primary.default \
    audio_policy.default \
    audio.primary.goldfish \
    audio_policy.goldfish \
    camera.goldfish \
    camera.goldfish.jpeg \
    fingerprint.goldfish \
    gps.goldfish \
    gralloc.goldfish \
    lights.goldfish \
    power.goldfish \
    sensors.goldfish \
    vibrator.goldfish, \
    $(PRODUCT_PACKAGES))
PRODUCT_COPY_FILES := $(filter-out \
    %android.hardware.sensor.%:% \
    device/generic/goldfish/% \
    device/generic/mini-emulator-% \
    device/google/atv/init.goldfish.rc:%, \
    $(PRODUCT_COPY_FILES))
PRODUCT_PROPERTY_OVERRIDES := $(filter-out \
    ro.adb.qemud=% \
    ro.kernel.qemu=% \
    ro.kernel.qemu.gles=% \
    qemu.hw.mainkeys=%, \
    $(PRODUCT_PROPERTY_OVERRIDES))
PRODUCT_DEFAULT_PROPERTY_OVERRIDES := $(filter-out \
    ro.adb.qemud=% \
    ro.kernel.qemu=% \
    ro.kernel.qemu.gles=% \
    qemu.hw.mainkeys=%, \
    $(PRODUCT_DEFAULT_PROPERTY_OVERRIDES))
PRODUCT_SYSTEM_PROPERTY_BLACKLIST += \
    ro.adb.qemud \
    ro.kernel.qemu \
    ro.kernel.qemu.gles \
    qemu.hw.mainkeys
PRODUCT_BUILD_PROP_OVERRIDES += TARGET_AAPT_CHARACTERISTICS=phone

# Build Station: target device identity override
PRODUCT_NAME := cm_M6T
PRODUCT_DEVICE := M6T
PRODUCT_BRAND := meizu
PRODUCT_MANUFACTURER := Meizu
PRODUCT_MODEL := M6T
PRODUCT_RELEASE_NAME := M6T
TARGET_OTA_ASSERT_DEVICE := M6T
PRODUCT_BUILD_PROP_OVERRIDES += \
    PRODUCT_NAME=cm_M6T \
    PRODUCT_DEVICE=M6T \
    TARGET_DEVICE=M6T
# Keep emulator/default HALs out, use stock MT6750 blobs, and do not publish
# Flyme shared libraries that are absent from this dump.
PRODUCT_COPY_FILES := $(filter-out \
    %:system/etc/permissions/com.meizu.camera.xml \
    %:system/lib/hw/audio.primary.default.so \
    %:system/lib64/hw/audio.primary.default.so \
    %:system/lib/hw/audio.primary.goldfish.so \
    %:system/lib64/hw/audio.primary.goldfish.so \
    %:system/lib/hw/audio_policy.default.so \
    %:system/lib64/hw/audio_policy.default.so \
    %:system/lib/hw/audio_policy.goldfish.so \
    %:system/lib64/hw/audio_policy.goldfish.so \
    %:system/lib/hw/camera.goldfish.so \
    %:system/lib64/hw/camera.goldfish.so \
    %:system/lib/hw/camera.goldfish.jpeg.so \
    %:system/lib64/hw/camera.goldfish.jpeg.so \
    %:system/lib/hw/camera.ranchu.so \
    %:system/lib64/hw/camera.ranchu.so \
    %:system/lib/hw/camera.ranchu.jpeg.so \
    %:system/lib64/hw/camera.ranchu.jpeg.so \
    %:system/lib/hw/fingerprint.goldfish.so \
    %:system/lib64/hw/fingerprint.goldfish.so \
    %:system/lib/hw/fingerprint.ranchu.so \
    %:system/lib64/hw/fingerprint.ranchu.so \
    %:system/lib/hw/gps.goldfish.so \
    %:system/lib64/hw/gps.goldfish.so \
    %:system/lib/hw/gps.ranchu.so \
    %:system/lib64/hw/gps.ranchu.so \
    %:system/lib/hw/lights.goldfish.so \
    %:system/lib64/hw/lights.goldfish.so \
    %:system/lib/hw/power.goldfish.so \
    %:system/lib64/hw/power.goldfish.so \
    %:system/lib/hw/sensors.goldfish.so \
    %:system/lib64/hw/sensors.goldfish.so \
    %:system/lib/hw/sensors.ranchu.so \
    %:system/lib64/hw/sensors.ranchu.so \
    %:system/lib/hw/vibrator.goldfish.so \
    %:system/lib64/hw/vibrator.goldfish.so \
    %:system/vendor/lib/hw/audio.primary.mt6750.so \
    %:system/vendor/lib64/hw/audio.primary.mt6750.so \
    %:system/vendor/lib64/hw/fingerprint.default.so \
    %:system/etc/permissions/android.hardware.fingerprint.xml, \
    $(PRODUCT_COPY_FILES))

PRODUCT_COPY_FILES += \
    vendor/meizu/M6T/proprietary/vendor/lib/hw/audio.primary.mt6750.so:system/vendor/lib/hw/audio.primary.mt6750.so \
    vendor/meizu/M6T/proprietary/vendor/lib64/hw/audio.primary.mt6750.so:system/vendor/lib64/hw/audio.primary.mt6750.so

# Build Station: final real-device hardware HAL cleanup after all product inheritance.
PRODUCT_PACKAGES := $(filter-out \
    audio.primary.default \
    audio.primary.goldfish \
    audio_policy.default \
    audio_policy.goldfish \
    gralloc.default \
    gralloc.goldfish \
    gralloc.ranchu \
    camera.goldfish \
    camera.goldfish.jpeg \
    camera.ranchu \
    camera.ranchu.jpeg \
    fingerprint.goldfish \
    fingerprint.ranchu \
    gps.goldfish \
    gps.ranchu \
    lights.goldfish \
    power.goldfish \
    sensors.goldfish \
    sensors.ranchu \
    vibrator.goldfish, \
    $(PRODUCT_PACKAGES))
PRODUCT_COPY_FILES := $(filter-out \
    device/generic/goldfish/% \
    device/generic/mini-emulator-% \
    device/google/atv/init.goldfish.rc:% \
    %:system/lib/hw/audio.primary.default.so \
    %:system/lib64/hw/audio.primary.default.so \
    %:system/vendor/lib/hw/audio.primary.default.so \
    %:system/vendor/lib64/hw/audio.primary.default.so \
    %:system/lib/hw/audio.primary.goldfish.so \
    %:system/lib64/hw/audio.primary.goldfish.so \
    %:system/vendor/lib/hw/audio.primary.goldfish.so \
    %:system/vendor/lib64/hw/audio.primary.goldfish.so \
    %:system/lib/hw/audio_policy.default.so \
    %:system/lib64/hw/audio_policy.default.so \
    %:system/vendor/lib/hw/audio_policy.default.so \
    %:system/vendor/lib64/hw/audio_policy.default.so \
    %:system/lib/hw/audio_policy.goldfish.so \
    %:system/lib64/hw/audio_policy.goldfish.so \
    %:system/vendor/lib/hw/audio_policy.goldfish.so \
    %:system/vendor/lib64/hw/audio_policy.goldfish.so \
    %:system/lib/hw/gralloc.default.so \
    %:system/lib64/hw/gralloc.default.so \
    %:system/vendor/lib/hw/gralloc.default.so \
    %:system/vendor/lib64/hw/gralloc.default.so \
    %:system/lib/hw/gralloc.goldfish.so \
    %:system/lib64/hw/gralloc.goldfish.so \
    %:system/vendor/lib/hw/gralloc.goldfish.so \
    %:system/vendor/lib64/hw/gralloc.goldfish.so \
    %:system/lib/hw/gralloc.ranchu.so \
    %:system/lib64/hw/gralloc.ranchu.so \
    %:system/vendor/lib/hw/gralloc.ranchu.so \
    %:system/vendor/lib64/hw/gralloc.ranchu.so \
    %:system/lib/hw/camera.goldfish.so \
    %:system/lib64/hw/camera.goldfish.so \
    %:system/vendor/lib/hw/camera.goldfish.so \
    %:system/vendor/lib64/hw/camera.goldfish.so \
    %:system/lib/hw/camera.goldfish.jpeg.so \
    %:system/lib64/hw/camera.goldfish.jpeg.so \
    %:system/vendor/lib/hw/camera.goldfish.jpeg.so \
    %:system/vendor/lib64/hw/camera.goldfish.jpeg.so \
    %:system/lib/hw/camera.ranchu.so \
    %:system/lib64/hw/camera.ranchu.so \
    %:system/vendor/lib/hw/camera.ranchu.so \
    %:system/vendor/lib64/hw/camera.ranchu.so \
    %:system/lib/hw/camera.ranchu.jpeg.so \
    %:system/lib64/hw/camera.ranchu.jpeg.so \
    %:system/vendor/lib/hw/camera.ranchu.jpeg.so \
    %:system/vendor/lib64/hw/camera.ranchu.jpeg.so \
    %:system/lib/hw/fingerprint.goldfish.so \
    %:system/lib64/hw/fingerprint.goldfish.so \
    %:system/vendor/lib/hw/fingerprint.goldfish.so \
    %:system/vendor/lib64/hw/fingerprint.goldfish.so \
    %:system/lib/hw/fingerprint.ranchu.so \
    %:system/lib64/hw/fingerprint.ranchu.so \
    %:system/vendor/lib/hw/fingerprint.ranchu.so \
    %:system/vendor/lib64/hw/fingerprint.ranchu.so \
    %:system/lib/hw/gps.goldfish.so \
    %:system/lib64/hw/gps.goldfish.so \
    %:system/vendor/lib/hw/gps.goldfish.so \
    %:system/vendor/lib64/hw/gps.goldfish.so \
    %:system/lib/hw/gps.ranchu.so \
    %:system/lib64/hw/gps.ranchu.so \
    %:system/vendor/lib/hw/gps.ranchu.so \
    %:system/vendor/lib64/hw/gps.ranchu.so \
    %:system/lib/hw/lights.goldfish.so \
    %:system/lib64/hw/lights.goldfish.so \
    %:system/vendor/lib/hw/lights.goldfish.so \
    %:system/vendor/lib64/hw/lights.goldfish.so \
    %:system/lib/hw/power.goldfish.so \
    %:system/lib64/hw/power.goldfish.so \
    %:system/vendor/lib/hw/power.goldfish.so \
    %:system/vendor/lib64/hw/power.goldfish.so \
    %:system/lib/hw/sensors.goldfish.so \
    %:system/lib64/hw/sensors.goldfish.so \
    %:system/vendor/lib/hw/sensors.goldfish.so \
    %:system/vendor/lib64/hw/sensors.goldfish.so \
    %:system/lib/hw/sensors.ranchu.so \
    %:system/lib64/hw/sensors.ranchu.so \
    %:system/vendor/lib/hw/sensors.ranchu.so \
    %:system/vendor/lib64/hw/sensors.ranchu.so \
    %:system/lib/hw/vibrator.goldfish.so \
    %:system/lib64/hw/vibrator.goldfish.so \
    %:system/vendor/lib/hw/vibrator.goldfish.so \
    %:system/vendor/lib64/hw/vibrator.goldfish.so \
    %:root/ueventd.goldfish.rc \
    %:root/ueventd.ranchu.rc, \
    $(PRODUCT_COPY_FILES))

# Build Station: final M6 hardware HAL cleanup after all product inheritance.
PRODUCT_PACKAGES := $(filter-out \
    audio.primary.default \
    audio.primary.goldfish \
    audio_policy.default \
    audio_policy.goldfish \
    gralloc.default \
    gralloc.goldfish \
    gralloc.ranchu \
    camera.goldfish \
    camera.goldfish.jpeg \
    camera.ranchu \
    camera.ranchu.jpeg \
    fingerprint.goldfish \
    fingerprint.ranchu \
    gps.goldfish \
    gps.ranchu \
    lights.goldfish \
    power.goldfish \
    sensors.goldfish \
    sensors.ranchu \
    vibrator.goldfish, \
    $(PRODUCT_PACKAGES))
PRODUCT_COPY_FILES := $(filter-out \
    device/generic/goldfish/% \
    device/generic/mini-emulator-% \
    device/google/atv/init.goldfish.rc:% \
    %:root/fstab.goldfish \
    %:root/fstab.ranchu \
    %:root/init.goldfish.rc \
    %:root/init.ranchu.rc \
    %:root/ueventd.goldfish.rc \
    %:root/ueventd.ranchu.rc \
    %:system/etc/init.goldfish.sh \
    %:system/usr/idc/goldfish_rotary.idc \
    %:system/etc/permissions/com.meizu.camera.xml \
    %:system/lib/hw/audio.primary.default.so \
    %:system/lib64/hw/audio.primary.default.so \
    %:system/vendor/lib/hw/audio.primary.default.so \
    %:system/vendor/lib64/hw/audio.primary.default.so \
    %:system/lib/hw/audio.primary.goldfish.so \
    %:system/lib64/hw/audio.primary.goldfish.so \
    %:system/vendor/lib/hw/audio.primary.goldfish.so \
    %:system/vendor/lib64/hw/audio.primary.goldfish.so \
    %:system/lib/hw/audio_policy.default.so \
    %:system/lib64/hw/audio_policy.default.so \
    %:system/vendor/lib/hw/audio_policy.default.so \
    %:system/vendor/lib64/hw/audio_policy.default.so \
    %:system/lib/hw/audio_policy.goldfish.so \
    %:system/lib64/hw/audio_policy.goldfish.so \
    %:system/vendor/lib/hw/audio_policy.goldfish.so \
    %:system/vendor/lib64/hw/audio_policy.goldfish.so \
    %:system/lib/hw/gralloc.default.so \
    %:system/lib64/hw/gralloc.default.so \
    %:system/vendor/lib/hw/gralloc.default.so \
    %:system/vendor/lib64/hw/gralloc.default.so \
    %:system/lib/hw/gralloc.goldfish.so \
    %:system/lib64/hw/gralloc.goldfish.so \
    %:system/vendor/lib/hw/gralloc.goldfish.so \
    %:system/vendor/lib64/hw/gralloc.goldfish.so \
    %:system/lib/hw/gralloc.ranchu.so \
    %:system/lib64/hw/gralloc.ranchu.so \
    %:system/vendor/lib/hw/gralloc.ranchu.so \
    %:system/vendor/lib64/hw/gralloc.ranchu.so \
    %:system/lib/hw/camera.goldfish.so \
    %:system/lib64/hw/camera.goldfish.so \
    %:system/lib/hw/camera.goldfish.jpeg.so \
    %:system/lib64/hw/camera.goldfish.jpeg.so \
    %:system/lib/hw/camera.ranchu.so \
    %:system/lib64/hw/camera.ranchu.so \
    %:system/lib/hw/camera.ranchu.jpeg.so \
    %:system/lib64/hw/camera.ranchu.jpeg.so \
    %:system/lib/hw/fingerprint.goldfish.so \
    %:system/lib64/hw/fingerprint.goldfish.so \
    %:system/lib/hw/fingerprint.ranchu.so \
    %:system/lib64/hw/fingerprint.ranchu.so \
    %:system/lib/hw/gps.goldfish.so \
    %:system/lib64/hw/gps.goldfish.so \
    %:system/lib/hw/gps.ranchu.so \
    %:system/lib64/hw/gps.ranchu.so \
    %:system/lib/hw/lights.goldfish.so \
    %:system/lib64/hw/lights.goldfish.so \
    %:system/lib/hw/power.goldfish.so \
    %:system/lib64/hw/power.goldfish.so \
    %:system/lib/hw/sensors.goldfish.so \
    %:system/lib64/hw/sensors.goldfish.so \
    %:system/lib/hw/sensors.ranchu.so \
    %:system/lib64/hw/sensors.ranchu.so \
    %:system/lib/hw/vibrator.goldfish.so \
    %:system/lib64/hw/vibrator.goldfish.so \
    %:system/vendor/lib/hw/gralloc.mt6755.so \
    %:system/vendor/lib64/hw/gralloc.mt6755.so \
    %:system/vendor/lib/hw/hwcomposer.mt6755.so \
    %:system/vendor/lib64/hw/hwcomposer.mt6755.so, \
    $(PRODUCT_COPY_FILES))
PRODUCT_CHARACTERISTICS := phone
# Build Station: CM product wrapper follows the same LOS15.1 first-boot isolation.
PRODUCT_PACKAGES := $(filter-out fingerprintd,$(PRODUCT_PACKAGES))
PRODUCT_PROPERTY_OVERRIDES := $(filter-out \
    ro.hardware.camera=% \
    ro.hardware.fingerprint=% \
    media.sf.omx-plugin=% \
    media.sf.extractor-plugin=% \
    ro.radio.noril=% \
    persist.radio.no_ril=% \
    gsm.version.ril-impl=% \
    persist.mediatek.fg.disable=%, \
    $(PRODUCT_PROPERTY_OVERRIDES))
PRODUCT_DEFAULT_PROPERTY_OVERRIDES := $(filter-out \
    ro.hardware.camera=% \
    ro.hardware.fingerprint=% \
    media.sf.omx-plugin=% \
    media.sf.extractor-plugin=% \
    ro.radio.noril=% \
    persist.radio.no_ril=% \
    gsm.version.ril-impl=% \
    persist.mediatek.fg.disable=%, \
    $(PRODUCT_DEFAULT_PROPERTY_OVERRIDES))
PRODUCT_SYSTEM_PROPERTY_BLACKLIST += \
    ro.hardware.camera \
    ro.hardware.fingerprint \
    media.sf.omx-plugin \
    media.sf.extractor-plugin \
    ro.radio.noril \
    persist.radio.no_ril \
    gsm.version.ril-impl \
    persist.mediatek.fg.disable
PRODUCT_COPY_FILES := $(filter-out \
    %:system/etc/permissions/android.hardware.camera.xml \
    %:system/etc/permissions/android.hardware.camera.flash-autofocus.xml \
    %:system/etc/permissions/android.hardware.camera.front.xml \
    %:system/etc/permissions/android.hardware.fingerprint.xml \
    %:system/etc/init/fingerprintd.rc \
    %:system/lib/hw/fingerprint.default.so \
    %:system/lib64/hw/fingerprint.default.so \
    %:system/vendor/lib/hw/camera.mt6750.so \
    %:system/vendor/lib64/hw/camera.mt6750.so \
    %:system/vendor/lib/hw/fingerprint.default.so \
    %:system/vendor/lib64/hw/fingerprint.default.so \
    %:system/lib/hw/swfingerprint.default.so \
    %:system/lib64/hw/swfingerprint.default.so \
    %:system/vendor/lib/hw/swfingerprint.default.so \
    %:system/vendor/lib64/hw/swfingerprint.default.so \
    %:system/etc/media_codecs.xml \
    %:system/vendor/etc/media_codecs.xml \
    %:system/vendor/etc/mtk_omx_core.cfg \
    %:system/vendor/lib/libMtkOmxVdecEx.so \
    %:system/vendor/lib64/libMtkOmxVdecEx.so, \
    $(PRODUCT_COPY_FILES))
PRODUCT_COPY_FILES += \
    device/meizu/m3_meizu_m6-common/configs/media_codecs_firstboot.xml:system/etc/media_codecs.xml \
    device/meizu/m3_meizu_m6-common/configs/media_codecs_firstboot.xml:system/vendor/etc/media_codecs.xml
# Build Station: M6 boot-unblock, do not publish broken sensors/soundtrigger HALs.
PRODUCT_PACKAGES := $(filter-out \
    android.hardware.sensors@1.0-impl.mtk \
    android.hardware.sensors@1.0-service.mtk \
    android.hardware.soundtrigger@2.0-impl \
    ,$(PRODUCT_PACKAGES))
PRODUCT_COPY_FILES := $(filter-out \
    %android.hardware.sensor.accelerometer.xml:% \
    %android.hardware.sensor.compass.xml:% \
    %android.hardware.sensor.gyroscope.xml:% \
    %android.hardware.sensor.light.xml:% \
    %android.hardware.sensor.proximity.xml:% \
    %android.hardware.sensor.stepcounter.xml:% \
    %android.hardware.sensor.stepdetector.xml:% \
    %sensors.mt6750.so:% \
    %android.hardware.sensors@1.0-impl.mtk.so:% \
    %android.hardware.sensors@1.0-service.mtk:% \
    %android.hardware.soundtrigger@2.0-impl.so:% \
    ,$(PRODUCT_COPY_FILES))

# Build Station: early ADB bring-up defaults
PRODUCT_SYSTEM_DEFAULT_PROPERTIES += \
    ro.secure=0 \
    ro.debuggable=1 \
    ro.adb.secure=0 \
    ro.zygote=zygote64
PRODUCT_DEFAULT_PROPERTY_OVERRIDES := $(filter-out ro.zygote=%,$(PRODUCT_DEFAULT_PROPERTY_OVERRIDES))
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += \
    ro.secure=0 \
    ro.debuggable=1 \
    ro.adb.secure=0 \
    ro.zygote=zygote64 \
    persist.sys.usb.config=adb \
    persist.service.adb.enable=1 \
    persist.sys.adb.shell=/system/bin/sh
