# Board-specific vendor copy rules. Keep destination paths aligned with the vendor image.

PRODUCT_COPY_FILES += \
    device/meizu/M6T/proprietary/bin/MPED:$(TARGET_COPY_OUT_VENDOR)/bin/MPED \
    device/meizu/M6T/proprietary/bin/MtkCodecService:$(TARGET_COPY_OUT_VENDOR)/bin/MtkCodecService \
    device/meizu/M6T/proprietary/bin/aal:$(TARGET_COPY_OUT_VENDOR)/bin/aal \
    device/meizu/M6T/proprietary/bin/aee:$(TARGET_COPY_OUT_VENDOR)/bin/aee \
    device/meizu/M6T/proprietary/bin/aee_archive:$(TARGET_COPY_OUT_VENDOR)/bin/aee_archive \
    device/meizu/M6T/proprietary/bin/aee_core_forwarder:$(TARGET_COPY_OUT_VENDOR)/bin/aee_core_forwarder \
    device/meizu/M6T/proprietary/bin/aee_dumpstate:$(TARGET_COPY_OUT_VENDOR)/bin/aee_dumpstate \
    device/meizu/M6T/proprietary/bin/akmd09911:$(TARGET_COPY_OUT_VENDOR)/bin/akmd09911 \
    device/meizu/M6T/proprietary/bin/akmd8963:$(TARGET_COPY_OUT_VENDOR)/bin/akmd8963 \
    device/meizu/M6T/proprietary/bin/akmd8975:$(TARGET_COPY_OUT_VENDOR)/bin/akmd8975 \
    device/meizu/M6T/proprietary/bin/ami304d:$(TARGET_COPY_OUT_VENDOR)/bin/ami304d \
    device/meizu/M6T/proprietary/bin/audiocmdservice_atci:$(TARGET_COPY_OUT_VENDOR)/bin/audiocmdservice_atci \
    device/meizu/M6T/proprietary/bin/autobt:$(TARGET_COPY_OUT_VENDOR)/bin/autobt \
    device/meizu/M6T/proprietary/bin/autokd:$(TARGET_COPY_OUT_VENDOR)/bin/autokd \
    device/meizu/M6T/proprietary/bin/batterywarning:$(TARGET_COPY_OUT_VENDOR)/bin/batterywarning \
    device/meizu/M6T/proprietary/bin/bmm050d:$(TARGET_COPY_OUT_VENDOR)/bin/bmm050d \
    device/meizu/M6T/proprietary/bin/boot_logo_updater:$(TARGET_COPY_OUT_VENDOR)/bin/boot_logo_updater \
    device/meizu/M6T/proprietary/bin/ccci_fsd:$(TARGET_COPY_OUT_VENDOR)/bin/ccci_fsd \
    device/meizu/M6T/proprietary/bin/ccci_mdinit:$(TARGET_COPY_OUT_VENDOR)/bin/ccci_mdinit \
    device/meizu/M6T/proprietary/bin/charon:$(TARGET_COPY_OUT_VENDOR)/bin/charon \
    device/meizu/M6T/proprietary/bin/dhcp6c:$(TARGET_COPY_OUT_VENDOR)/bin/dhcp6c \
    device/meizu/M6T/proprietary/bin/dhcp6ctl:$(TARGET_COPY_OUT_VENDOR)/bin/dhcp6ctl \
    device/meizu/M6T/proprietary/bin/dhcp6s:$(TARGET_COPY_OUT_VENDOR)/bin/dhcp6s \
    device/meizu/M6T/proprietary/bin/dmlog:$(TARGET_COPY_OUT_VENDOR)/bin/dmlog \
    device/meizu/M6T/proprietary/bin/downloader:$(TARGET_COPY_OUT_VENDOR)/bin/downloader \
    device/meizu/M6T/proprietary/bin/emdlogger1:$(TARGET_COPY_OUT_VENDOR)/bin/emdlogger1 \
    device/meizu/M6T/proprietary/bin/emdlogger2:$(TARGET_COPY_OUT_VENDOR)/bin/emdlogger2 \
    device/meizu/M6T/proprietary/bin/emdlogger3:$(TARGET_COPY_OUT_VENDOR)/bin/emdlogger3 \
    device/meizu/M6T/proprietary/bin/emdlogger5:$(TARGET_COPY_OUT_VENDOR)/bin/emdlogger5 \
    device/meizu/M6T/proprietary/bin/epdg_wod:$(TARGET_COPY_OUT_VENDOR)/bin/epdg_wod \
    device/meizu/M6T/proprietary/bin/factory:$(TARGET_COPY_OUT_VENDOR)/bin/factory \
    device/meizu/M6T/proprietary/bin/flashlessd:$(TARGET_COPY_OUT_VENDOR)/bin/flashlessd \
    device/meizu/M6T/proprietary/bin/fsck_msdos_mtk:$(TARGET_COPY_OUT_VENDOR)/bin/fsck_msdos_mtk \
    device/meizu/M6T/proprietary/bin/fuelgauged:$(TARGET_COPY_OUT_VENDOR)/bin/fuelgauged \
    device/meizu/M6T/proprietary/bin/fuelgauged_nvram:$(TARGET_COPY_OUT_VENDOR)/bin/fuelgauged_nvram \
    device/meizu/M6T/proprietary/bin/ged_srv:$(TARGET_COPY_OUT_VENDOR)/bin/ged_srv \
    device/meizu/M6T/proprietary/bin/geomagneticd:$(TARGET_COPY_OUT_VENDOR)/bin/geomagneticd \
    device/meizu/M6T/proprietary/bin/gsm0710muxd:$(TARGET_COPY_OUT_VENDOR)/bin/gsm0710muxd \
    device/meizu/M6T/proprietary/bin/gsm0710muxdmd2:$(TARGET_COPY_OUT_VENDOR)/bin/gsm0710muxdmd2 \
    device/meizu/M6T/proprietary/bin/ifaad:$(TARGET_COPY_OUT_VENDOR)/bin/ifaad \
    device/meizu/M6T/proprietary/bin/ipsec:$(TARGET_COPY_OUT_VENDOR)/bin/ipsec \
    device/meizu/M6T/proprietary/bin/ipsec_mon:$(TARGET_COPY_OUT_VENDOR)/bin/ipsec_mon \
    device/meizu/M6T/proprietary/bin/kpoc_charger:$(TARGET_COPY_OUT_VENDOR)/bin/kpoc_charger \
    device/meizu/M6T/proprietary/bin/lcdc_screen_cap:$(TARGET_COPY_OUT_VENDOR)/bin/lcdc_screen_cap \
    device/meizu/M6T/proprietary/bin/lsm303md:$(TARGET_COPY_OUT_VENDOR)/bin/lsm303md \
    device/meizu/M6T/proprietary/bin/magd:$(TARGET_COPY_OUT_VENDOR)/bin/magd \
    device/meizu/M6T/proprietary/bin/matv:$(TARGET_COPY_OUT_VENDOR)/bin/matv \
    device/meizu/M6T/proprietary/bin/mbimd:$(TARGET_COPY_OUT_VENDOR)/bin/mbimd \
    device/meizu/M6T/proprietary/bin/mc6420d:$(TARGET_COPY_OUT_VENDOR)/bin/mc6420d \
    device/meizu/M6T/proprietary/bin/md_ctrl:$(TARGET_COPY_OUT_VENDOR)/bin/md_ctrl \
    device/meizu/M6T/proprietary/bin/mdlogger:$(TARGET_COPY_OUT_VENDOR)/bin/mdlogger \
    device/meizu/M6T/proprietary/bin/memorydumper:$(TARGET_COPY_OUT_VENDOR)/bin/memorydumper \
    device/meizu/M6T/proprietary/bin/meta_tst:$(TARGET_COPY_OUT_VENDOR)/bin/meta_tst \
    device/meizu/M6T/proprietary/bin/mfv_ut:$(TARGET_COPY_OUT_VENDOR)/bin/mfv_ut \
    device/meizu/M6T/proprietary/bin/mnld:$(TARGET_COPY_OUT_VENDOR)/bin/mnld \
    device/meizu/M6T/proprietary/bin/mobile_log_d:$(TARGET_COPY_OUT_VENDOR)/bin/mobile_log_d \
    device/meizu/M6T/proprietary/bin/msensord:$(TARGET_COPY_OUT_VENDOR)/bin/msensord \
    device/meizu/M6T/proprietary/bin/mtk_agpsd:$(TARGET_COPY_OUT_VENDOR)/bin/mtk_agpsd \
    device/meizu/M6T/proprietary/bin/mtkmal:$(TARGET_COPY_OUT_VENDOR)/bin/mtkmal \
    device/meizu/M6T/proprietary/bin/mtkrild:$(TARGET_COPY_OUT_VENDOR)/bin/mtkrild \
    device/meizu/M6T/proprietary/bin/mtkrildmd2:$(TARGET_COPY_OUT_VENDOR)/bin/mtkrildmd2 \
    device/meizu/M6T/proprietary/bin/muxreport:$(TARGET_COPY_OUT_VENDOR)/bin/muxreport \
    device/meizu/M6T/proprietary/bin/netdiag:$(TARGET_COPY_OUT_VENDOR)/bin/netdiag \
    device/meizu/M6T/proprietary/bin/nvram_agent_binder:$(TARGET_COPY_OUT_VENDOR)/bin/nvram_agent_binder \
    device/meizu/M6T/proprietary/bin/nvram_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/nvram_daemon \
    device/meizu/M6T/proprietary/bin/orientationd:$(TARGET_COPY_OUT_VENDOR)/bin/orientationd \
    device/meizu/M6T/proprietary/bin/perf_native_test:$(TARGET_COPY_OUT_VENDOR)/bin/perf_native_test \
    device/meizu/M6T/proprietary/bin/pq:$(TARGET_COPY_OUT_VENDOR)/bin/pq \
    device/meizu/M6T/proprietary/bin/program_binary_builder:$(TARGET_COPY_OUT_VENDOR)/bin/program_binary_builder \
    device/meizu/M6T/proprietary/bin/program_binary_service:$(TARGET_COPY_OUT_VENDOR)/bin/program_binary_service \
    device/meizu/M6T/proprietary/bin/radvd:$(TARGET_COPY_OUT_VENDOR)/bin/radvd \
    device/meizu/M6T/proprietary/bin/resize_ext4:$(TARGET_COPY_OUT_VENDOR)/bin/resize_ext4 \
    device/meizu/M6T/proprietary/bin/rilproxy:$(TARGET_COPY_OUT_VENDOR)/bin/rilproxy \
    device/meizu/M6T/proprietary/bin/rs2spir:$(TARGET_COPY_OUT_VENDOR)/bin/rs2spir \
    device/meizu/M6T/proprietary/bin/rtt:$(TARGET_COPY_OUT_VENDOR)/bin/rtt \
    device/meizu/M6T/proprietary/bin/s62xd:$(TARGET_COPY_OUT_VENDOR)/bin/s62xd \
    device/meizu/M6T/proprietary/bin/slpd:$(TARGET_COPY_OUT_VENDOR)/bin/slpd \
    device/meizu/M6T/proprietary/bin/sn:$(TARGET_COPY_OUT_VENDOR)/bin/sn \
    device/meizu/M6T/proprietary/bin/spir2cl:$(TARGET_COPY_OUT_VENDOR)/bin/spir2cl \
    device/meizu/M6T/proprietary/bin/spm_loader:$(TARGET_COPY_OUT_VENDOR)/bin/spm_loader \
    device/meizu/M6T/proprietary/bin/starter:$(TARGET_COPY_OUT_VENDOR)/bin/starter \
    device/meizu/M6T/proprietary/bin/statusd:$(TARGET_COPY_OUT_VENDOR)/bin/statusd \
    device/meizu/M6T/proprietary/bin/stp_dump3:$(TARGET_COPY_OUT_VENDOR)/bin/stp_dump3 \
    device/meizu/M6T/proprietary/bin/stroke:$(TARGET_COPY_OUT_VENDOR)/bin/stroke \
    device/meizu/M6T/proprietary/bin/superumount:$(TARGET_COPY_OUT_VENDOR)/bin/superumount \
    device/meizu/M6T/proprietary/bin/sysenv_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/sysenv_daemon \
    device/meizu/M6T/proprietary/bin/teei_daemon:$(TARGET_COPY_OUT_VENDOR)/bin/teei_daemon \
    device/meizu/M6T/proprietary/bin/terservice:$(TARGET_COPY_OUT_VENDOR)/bin/terservice \
    device/meizu/M6T/proprietary/bin/tertestclient:$(TARGET_COPY_OUT_VENDOR)/bin/tertestclient \
    device/meizu/M6T/proprietary/bin/thermal:$(TARGET_COPY_OUT_VENDOR)/bin/thermal \
    device/meizu/M6T/proprietary/bin/thermal_manager:$(TARGET_COPY_OUT_VENDOR)/bin/thermal_manager \
    device/meizu/M6T/proprietary/bin/thermald:$(TARGET_COPY_OUT_VENDOR)/bin/thermald \
    device/meizu/M6T/proprietary/bin/thermalindicator:$(TARGET_COPY_OUT_VENDOR)/bin/thermalindicator \
    device/meizu/M6T/proprietary/bin/thermalloadalgod:$(TARGET_COPY_OUT_VENDOR)/bin/thermalloadalgod \
    device/meizu/M6T/proprietary/bin/viaradiooptions:$(TARGET_COPY_OUT_VENDOR)/bin/viaradiooptions \
    device/meizu/M6T/proprietary/bin/viarild:$(TARGET_COPY_OUT_VENDOR)/bin/viarild \
    device/meizu/M6T/proprietary/bin/volte_imcb:$(TARGET_COPY_OUT_VENDOR)/bin/volte_imcb \
    device/meizu/M6T/proprietary/bin/volte_stack:$(TARGET_COPY_OUT_VENDOR)/bin/volte_stack \
    device/meizu/M6T/proprietary/bin/volte_ua:$(TARGET_COPY_OUT_VENDOR)/bin/volte_ua \
    device/meizu/M6T/proprietary/bin/vtservice:$(TARGET_COPY_OUT_VENDOR)/bin/vtservice \
    device/meizu/M6T/proprietary/bin/wfca:$(TARGET_COPY_OUT_VENDOR)/bin/wfca \
    device/meizu/M6T/proprietary/bin/wifi2agps:$(TARGET_COPY_OUT_VENDOR)/bin/wifi2agps \
    device/meizu/M6T/proprietary/bin/wmt_concurrency:$(TARGET_COPY_OUT_VENDOR)/bin/wmt_concurrency \
    device/meizu/M6T/proprietary/bin/wmt_launcher:$(TARGET_COPY_OUT_VENDOR)/bin/wmt_launcher \
    device/meizu/M6T/proprietary/bin/wmt_loader:$(TARGET_COPY_OUT_VENDOR)/bin/wmt_loader \
    device/meizu/M6T/proprietary/bin/wmt_loopback:$(TARGET_COPY_OUT_VENDOR)/bin/wmt_loopback \
    device/meizu/M6T/proprietary/etc/audio_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_device.xml \
    device/meizu/M6T/proprietary/etc/audio_em.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_em.xml \
    device/meizu/M6T/proprietary/etc/audio_param/AudioParamOptions.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions.xml \
    device/meizu/M6T/proprietary/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    device/meizu/M6T/proprietary/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    device/meizu/M6T/proprietary/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    device/meizu/M6T/proprietary/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    device/meizu/M6T/proprietary/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    device/meizu/M6T/proprietary/etc/audio_policy.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy.conf \
    device/meizu/M6T/proprietary/etc/permissions/android.hardware.fingerprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.fingerprint.xml \
    device/meizu/M6T/proprietary/etc/permissions/flyme.hardware.screen.bluelightreduction.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/flyme.hardware.screen.bluelightreduction.xml \
    device/meizu/M6T/proprietary/firmware/ROMv2_lm_patch_1_0_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ROMv2_lm_patch_1_0_hdr.bin \
    device/meizu/M6T/proprietary/firmware/ROMv2_lm_patch_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ROMv2_lm_patch_1_1_hdr.bin \
    device/meizu/M6T/proprietary/firmware/WIFI_RAM_CODE_6755:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_6755 \
    device/meizu/M6T/proprietary/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    device/meizu/M6T/proprietary/firmware/catcher_filter_1_ulwctg_n.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/catcher_filter_1_ulwctg_n.bin \
    device/meizu/M6T/proprietary/firmware/catcher_filter_3_3g_n.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/catcher_filter_3_3g_n.bin \
    device/meizu/M6T/proprietary/firmware/customfilter/catcher_filter_1_ulwctg_n_C2KOnly_Test.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/customfilter/catcher_filter_1_ulwctg_n_C2KOnly_Test.bin \
    device/meizu/M6T/proprietary/firmware/customfilter/catcher_filter_1_ulwctg_n_Default_Embms.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/customfilter/catcher_filter_1_ulwctg_n_Default_Embms.bin \
    device/meizu/M6T/proprietary/firmware/customfilter/catcher_filter_1_ulwctg_n_Default_IPAllOff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/customfilter/catcher_filter_1_ulwctg_n_Default_IPAllOff.bin \
    device/meizu/M6T/proprietary/firmware/customfilter/catcher_filter_1_ulwctg_n_FullLog.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/customfilter/catcher_filter_1_ulwctg_n_FullLog.bin \
    device/meizu/M6T/proprietary/firmware/customfilter/catcher_filter_1_ulwctg_n_SlimLog_DspAllOff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/customfilter/catcher_filter_1_ulwctg_n_SlimLog_DspAllOff.bin \
    device/meizu/M6T/proprietary/firmware/customfilter/catcher_filter_1_ulwctg_n__Default.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/customfilter/catcher_filter_1_ulwctg_n__Default.bin \
    device/meizu/M6T/proprietary/firmware/customfilter/catcher_filter_1_ulwctg_n_meta.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/customfilter/catcher_filter_1_ulwctg_n_meta.bin \
    device/meizu/M6T/proprietary/firmware/em_filter_1_ulwctg_n.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/em_filter_1_ulwctg_n.bin \
    device/meizu/M6T/proprietary/firmware/pcm_deepidle_by_mp1_m.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_deepidle_by_mp1_m.bin \
    device/meizu/M6T/proprietary/firmware/pcm_deepidle_by_mp1_r.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_deepidle_by_mp1_r.bin \
    device/meizu/M6T/proprietary/firmware/pcm_deepidle_m.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_deepidle_m.bin \
    device/meizu/M6T/proprietary/firmware/pcm_deepidle_r.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_deepidle_r.bin \
    device/meizu/M6T/proprietary/firmware/pcm_mcdi_ddrdfs_m.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_mcdi_ddrdfs_m.bin \
    device/meizu/M6T/proprietary/firmware/pcm_sodi_ddrdfs_by_mp1_m.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_sodi_ddrdfs_by_mp1_m.bin \
    device/meizu/M6T/proprietary/firmware/pcm_sodi_ddrdfs_by_mp1_r.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_sodi_ddrdfs_by_mp1_r.bin \
    device/meizu/M6T/proprietary/firmware/pcm_sodi_ddrdfs_m.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_sodi_ddrdfs_m.bin \
    device/meizu/M6T/proprietary/firmware/pcm_sodi_ddrdfs_r.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_sodi_ddrdfs_r.bin \
    device/meizu/M6T/proprietary/firmware/pcm_suspend_by_mp1_m.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_suspend_by_mp1_m.bin \
    device/meizu/M6T/proprietary/firmware/pcm_suspend_by_mp1_r.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_suspend_by_mp1_r.bin \
    device/meizu/M6T/proprietary/firmware/pcm_suspend_m.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_suspend_m.bin \
    device/meizu/M6T/proprietary/firmware/pcm_suspend_r.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/pcm_suspend_r.bin \
    device/meizu/M6T/proprietary/firmware/wifi_fw.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/wifi_fw.cfg \
    device/meizu/M6T/proprietary/lib/drm/libdrmctaplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/drm/libdrmctaplugin.so \
    device/meizu/M6T/proprietary/lib/drm/libdrmmtkplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib/drm/libdrmmtkplugin.so \
    device/meizu/M6T/proprietary/lib/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib/egl/libGLES_mali.so \
    device/meizu/M6T/proprietary/lib/hw/audio.primary.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.primary.mt6750.so \
    device/meizu/M6T/proprietary/lib/hw/audio.r_submix.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.r_submix.mt6750.so \
    device/meizu/M6T/proprietary/lib/hw/audio.usb.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/audio.usb.mt6750.so \
    device/meizu/M6T/proprietary/lib/hw/camera.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/camera.mt6750.so \
    device/meizu/M6T/proprietary/lib/hw/gatekeeper.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gatekeeper.mt6750.so \
    device/meizu/M6T/proprietary/lib/hw/gps.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gps.mt6750.so \
    device/meizu/M6T/proprietary/lib/hw/gralloc.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/gralloc.mt6750.so \
    device/meizu/M6T/proprietary/lib/hw/hwcomposer.mt6755.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/hwcomposer.mt6755.so \
    device/meizu/M6T/proprietary/lib/hw/keystore.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/keystore.mt6750.so \
    device/meizu/M6T/proprietary/lib/hw/lights.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/lights.mt6750.so \
    device/meizu/M6T/proprietary/lib/hw/memtrack.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/memtrack.mt6750.so \
    device/meizu/M6T/proprietary/lib/hw/sensors.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.mt6750.so \
    device/meizu/M6T/proprietary/lib/lib3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib3a.so \
    device/meizu/M6T/proprietary/lib/lib3a_core1.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib3a_core1.so \
    device/meizu/M6T/proprietary/lib/lib3a_core2.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib3a_core2.so \
    device/meizu/M6T/proprietary/lib/lib3a_sample.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib3a_sample.so \
    device/meizu/M6T/proprietary/lib/libBnMtkCodec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libBnMtkCodec.so \
    device/meizu/M6T/proprietary/lib/libClearMotionFW.so:$(TARGET_COPY_OUT_VENDOR)/lib/libClearMotionFW.so \
    device/meizu/M6T/proprietary/lib/libDR.so:$(TARGET_COPY_OUT_VENDOR)/lib/libDR.so \
    device/meizu/M6T/proprietary/lib/libDepthBokehEffect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libDepthBokehEffect.so \
    device/meizu/M6T/proprietary/lib/libDepthBokehEffectBase.so:$(TARGET_COPY_OUT_VENDOR)/lib/libDepthBokehEffectBase.so \
    device/meizu/M6T/proprietary/lib/libHEVCdec_sa.ca7.android.so:$(TARGET_COPY_OUT_VENDOR)/lib/libHEVCdec_sa.ca7.android.so \
    device/meizu/M6T/proprietary/lib/libJpgDecPipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libJpgDecPipe.so \
    device/meizu/M6T/proprietary/lib/libJpgEncPipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libJpgEncPipe.so \
    device/meizu/M6T/proprietary/lib/libMiraVision_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMiraVision_jni.so \
    device/meizu/M6T/proprietary/lib/libMtkOmxAdpcmDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxAdpcmDec.so \
    device/meizu/M6T/proprietary/lib/libMtkOmxAdpcmEnc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxAdpcmEnc.so \
    device/meizu/M6T/proprietary/lib/libMtkOmxApeDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxApeDec.so \
    device/meizu/M6T/proprietary/lib/libMtkOmxCore.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxCore.so \
    device/meizu/M6T/proprietary/lib/libMtkOmxFlacDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxFlacDec.so \
    device/meizu/M6T/proprietary/lib/libMtkOmxG711Dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxG711Dec.so \
    device/meizu/M6T/proprietary/lib/libMtkOmxGsmDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxGsmDec.so \
    device/meizu/M6T/proprietary/lib/libMtkOmxMp3Dec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxMp3Dec.so \
    device/meizu/M6T/proprietary/lib/libMtkOmxRawDec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxRawDec.so \
    device/meizu/M6T/proprietary/lib/libMtkOmxVdecEx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxVdecEx.so \
    device/meizu/M6T/proprietary/lib/libMtkOmxVenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxVenc.so \
    device/meizu/M6T/proprietary/lib/libMtkOmxVorbisEnc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkOmxVorbisEnc.so \
    device/meizu/M6T/proprietary/lib/libMtkVideoSpeedEffect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libMtkVideoSpeedEffect.so \
    device/meizu/M6T/proprietary/lib/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCL.so \
    device/meizu/M6T/proprietary/lib/libOpenCLIcd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libOpenCLIcd.so \
    device/meizu/M6T/proprietary/lib/libPQDCjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libPQDCjni.so \
    device/meizu/M6T/proprietary/lib/libPQjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libPQjni.so \
    device/meizu/M6T/proprietary/lib/libRSDriver_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libRSDriver_mtk.so \
    device/meizu/M6T/proprietary/lib/libSonyIMX230PdafLibrary.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSonyIMX230PdafLibrary.so \
    device/meizu/M6T/proprietary/lib/libSwJpgCodec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libSwJpgCodec.so \
    device/meizu/M6T/proprietary/lib/libaal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaal.so \
    device/meizu/M6T/proprietary/lib/libaal_cust.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaal_cust.so \
    device/meizu/M6T/proprietary/lib/libacdk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libacdk.so \
    device/meizu/M6T/proprietary/lib/libaed.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaed.so \
    device/meizu/M6T/proprietary/lib/libamr_wrap.so:$(TARGET_COPY_OUT_VENDOR)/lib/libamr_wrap.so \
    device/meizu/M6T/proprietary/lib/libamrvt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libamrvt.so \
    device/meizu/M6T/proprietary/lib/libarcsoft_beautyshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libarcsoft_beautyshot.so \
    device/meizu/M6T/proprietary/lib/libarcsoft_high_dynamic_range.so:$(TARGET_COPY_OUT_VENDOR)/lib/libarcsoft_high_dynamic_range.so \
    device/meizu/M6T/proprietary/lib/libarcsoft_low_light_shot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libarcsoft_low_light_shot.so \
    device/meizu/M6T/proprietary/lib/libarcsoft_makeup.so:$(TARGET_COPY_OUT_VENDOR)/lib/libarcsoft_makeup.so \
    device/meizu/M6T/proprietary/lib/libatvctrlservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libatvctrlservice.so \
    device/meizu/M6T/proprietary/lib/libaudio_param_parser.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudio_param_parser.so \
    device/meizu/M6T/proprietary/lib/libaudiocompensationfilter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocompensationfilter.so \
    device/meizu/M6T/proprietary/lib/libaudiocomponentengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocomponentengine.so \
    device/meizu/M6T/proprietary/lib/libaudiocustparam.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiocustparam.so \
    device/meizu/M6T/proprietary/lib/libaudiodcrflt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiodcrflt.so \
    device/meizu/M6T/proprietary/lib/libaudiomtkdcremoval.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiomtkdcremoval.so \
    device/meizu/M6T/proprietary/lib/libaudiosetting.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiosetting.so \
    device/meizu/M6T/proprietary/lib/libaudiotoolkit.so:$(TARGET_COPY_OUT_VENDOR)/lib/libaudiotoolkit.so \
    device/meizu/M6T/proprietary/lib/libawb_wrap.so:$(TARGET_COPY_OUT_VENDOR)/lib/libawb_wrap.so \
    device/meizu/M6T/proprietary/lib/libbessound_hd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbessound_hd_mtk.so \
    device/meizu/M6T/proprietary/lib/libblisrc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libblisrc.so \
    device/meizu/M6T/proprietary/lib/libblisrc32.so:$(TARGET_COPY_OUT_VENDOR)/lib/libblisrc32.so \
    device/meizu/M6T/proprietary/lib/libbluetooth_hw_test.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbluetooth_hw_test.so \
    device/meizu/M6T/proprietary/lib/libbluetooth_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbluetooth_mtk.so \
    device/meizu/M6T/proprietary/lib/libbluetooth_mtk_pure.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbluetooth_mtk_pure.so \
    device/meizu/M6T/proprietary/lib/libbluetooth_relayer.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbluetooth_relayer.so \
    device/meizu/M6T/proprietary/lib/libbluetoothem_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbluetoothem_mtk.so \
    device/meizu/M6T/proprietary/lib/libbt-aptX-ARM-4.2.2.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbt-aptX-ARM-4.2.2.so \
    device/meizu/M6T/proprietary/lib/libbt-vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbt-vendor.so \
    device/meizu/M6T/proprietary/lib/libbwc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbwc.so \
    device/meizu/M6T/proprietary/lib/libc2kril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2kril.so \
    device/meizu/M6T/proprietary/lib/libc2kutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libc2kutils.so \
    device/meizu/M6T/proprietary/lib/libcam.camadapter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.camadapter.so \
    device/meizu/M6T/proprietary/lib/libcam.camarcsoft.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.camarcsoft.so \
    device/meizu/M6T/proprietary/lib/libcam.camnode.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.camnode.so \
    device/meizu/M6T/proprietary/lib/libcam.camshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.camshot.so \
    device/meizu/M6T/proprietary/lib/libcam.client.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.client.so \
    device/meizu/M6T/proprietary/lib/libcam.common.meizu.platform.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.common.meizu.platform.so \
    device/meizu/M6T/proprietary/lib/libcam.common.meizu.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.common.meizu.so \
    device/meizu/M6T/proprietary/lib/libcam.device1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.device1.so \
    device/meizu/M6T/proprietary/lib/libcam.device3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.device3.so \
    device/meizu/M6T/proprietary/lib/libcam.exif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.exif.so \
    device/meizu/M6T/proprietary/lib/libcam.exif.v3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.exif.v3.so \
    device/meizu/M6T/proprietary/lib/libcam.hal3a.v3.dng.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.hal3a.v3.dng.so \
    device/meizu/M6T/proprietary/lib/libcam.hal3a.v3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.hal3a.v3.so \
    device/meizu/M6T/proprietary/lib/libcam.halsensor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.halsensor.so \
    device/meizu/M6T/proprietary/lib/libcam.iopipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.iopipe.so \
    device/meizu/M6T/proprietary/lib/libcam.jni.lomohaljni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.jni.lomohaljni.so \
    device/meizu/M6T/proprietary/lib/libcam.metadata.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.metadata.so \
    device/meizu/M6T/proprietary/lib/libcam.metadataprovider.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.metadataprovider.so \
    device/meizu/M6T/proprietary/lib/libcam.paramsmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.paramsmgr.so \
    device/meizu/M6T/proprietary/lib/libcam.utils.cpuctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.utils.cpuctrl.so \
    device/meizu/M6T/proprietary/lib/libcam.utils.sensorlistener.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.utils.sensorlistener.so \
    device/meizu/M6T/proprietary/lib/libcam.utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam.utils.so \
    device/meizu/M6T/proprietary/lib/libcam1_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam1_utils.so \
    device/meizu/M6T/proprietary/lib/libcam3_app.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam3_app.so \
    device/meizu/M6T/proprietary/lib/libcam3_hwnode.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam3_hwnode.so \
    device/meizu/M6T/proprietary/lib/libcam3_hwpipeline.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam3_hwpipeline.so \
    device/meizu/M6T/proprietary/lib/libcam3_pipeline.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam3_pipeline.so \
    device/meizu/M6T/proprietary/lib/libcam3_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam3_utils.so \
    device/meizu/M6T/proprietary/lib/libcam_hwutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam_hwutils.so \
    device/meizu/M6T/proprietary/lib/libcam_mmp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam_mmp.so \
    device/meizu/M6T/proprietary/lib/libcam_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam_platform.so \
    device/meizu/M6T/proprietary/lib/libcam_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcam_utils.so \
    device/meizu/M6T/proprietary/lib/libcamalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcamalgo.so \
    device/meizu/M6T/proprietary/lib/libcamdrv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcamdrv.so \
    device/meizu/M6T/proprietary/lib/libcamera_bokehutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcamera_bokehutils.so \
    device/meizu/M6T/proprietary/lib/libcameracustom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcameracustom.so \
    device/meizu/M6T/proprietary/lib/libccci_util.so:$(TARGET_COPY_OUT_VENDOR)/lib/libccci_util.so \
    device/meizu/M6T/proprietary/lib/libcharon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcharon.so \
    device/meizu/M6T/proprietary/lib/libcomutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcomutils.so \
    device/meizu/M6T/proprietary/lib/libcrypto-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcrypto-ss.so \
    device/meizu/M6T/proprietary/lib/libcurl-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcurl-ss.so \
    device/meizu/M6T/proprietary/lib/libcustom_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcustom_jni.so \
    device/meizu/M6T/proprietary/lib/libcustom_nvram.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcustom_nvram.so \
    device/meizu/M6T/proprietary/lib/libcustom_prop.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcustom_prop.so \
    device/meizu/M6T/proprietary/lib/libcvsd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libcvsd_mtk.so \
    device/meizu/M6T/proprietary/lib/libdirect-coredump.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdirect-coredump.so \
    device/meizu/M6T/proprietary/lib/libdngop.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdngop.so \
    device/meizu/M6T/proprietary/lib/libdpframework.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdpframework.so \
    device/meizu/M6T/proprietary/lib/libdrmmtkutil.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmmtkutil.so \
    device/meizu/M6T/proprietary/lib/libdrmmtkwhitelist.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdrmmtkwhitelist.so \
    device/meizu/M6T/proprietary/lib/libeffect.facebeautypp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libeffect.facebeautypp.so \
    device/meizu/M6T/proprietary/lib/libeffecthal.JPG.so:$(TARGET_COPY_OUT_VENDOR)/lib/libeffecthal.JPG.so \
    device/meizu/M6T/proprietary/lib/libeffecthal.base.so:$(TARGET_COPY_OUT_VENDOR)/lib/libeffecthal.base.so \
    device/meizu/M6T/proprietary/lib/libem_audio_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libem_audio_jni.so \
    device/meizu/M6T/proprietary/lib/libem_bt_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libem_bt_jni.so \
    device/meizu/M6T/proprietary/lib/libem_gpio_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libem_gpio_jni.so \
    device/meizu/M6T/proprietary/lib/libem_lte_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libem_lte_jni.so \
    device/meizu/M6T/proprietary/lib/libem_mbim_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libem_mbim_jni.so \
    device/meizu/M6T/proprietary/lib/libem_modem_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libem_modem_jni.so \
    device/meizu/M6T/proprietary/lib/libem_sensor_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libem_sensor_jni.so \
    device/meizu/M6T/proprietary/lib/libem_support_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libem_support_jni.so \
    device/meizu/M6T/proprietary/lib/libem_usb_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libem_usb_jni.so \
    device/meizu/M6T/proprietary/lib/libem_wifi_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libem_wifi_jni.so \
    device/meizu/M6T/proprietary/lib/libfeatureio.cfb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfeatureio.cfb.so \
    device/meizu/M6T/proprietary/lib/libfeatureio.featurefactory.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfeatureio.featurefactory.so \
    device/meizu/M6T/proprietary/lib/libfeatureio.jpg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfeatureio.jpg.so \
    device/meizu/M6T/proprietary/lib/libfeatureio.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfeatureio.so \
    device/meizu/M6T/proprietary/lib/libfeatureiodrv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfeatureiodrv.so \
    device/meizu/M6T/proprietary/lib/libfgauge.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfgauge.so \
    device/meizu/M6T/proprietary/lib/libfile_op.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfile_op.so \
    device/meizu/M6T/proprietary/lib/libfilter_effects.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfilter_effects.so \
    device/meizu/M6T/proprietary/lib/libfmjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfmjni.so \
    device/meizu/M6T/proprietary/lib/libfusion.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfusion.so \
    device/meizu/M6T/proprietary/lib/libgas.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgas.so \
    device/meizu/M6T/proprietary/lib/libged.so:$(TARGET_COPY_OUT_VENDOR)/lib/libged.so \
    device/meizu/M6T/proprietary/lib/libgpu_aux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgpu_aux.so \
    device/meizu/M6T/proprietary/lib/libgralloc_extra.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgralloc_extra.so \
    device/meizu/M6T/proprietary/lib/libgui_ext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libgui_ext.so \
    device/meizu/M6T/proprietary/lib/libh264enc_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libh264enc_sa.ca7.so \
    device/meizu/M6T/proprietary/lib/libh264enc_sb.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libh264enc_sb.ca7.so \
    device/meizu/M6T/proprietary/lib/libhdrproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhdrproc.so \
    device/meizu/M6T/proprietary/lib/libhwm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhwm.so \
    device/meizu/M6T/proprietary/lib/libhydra.so:$(TARGET_COPY_OUT_VENDOR)/lib/libhydra.so \
    device/meizu/M6T/proprietary/lib/libifaa_daemon.so:$(TARGET_COPY_OUT_VENDOR)/lib/libifaa_daemon.so \
    device/meizu/M6T/proprietary/lib/libimageio.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimageio.so \
    device/meizu/M6T/proprietary/lib/libimageio_plat_drv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimageio_plat_drv.so \
    device/meizu/M6T/proprietary/lib/libimsg_log.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimsg_log.so \
    device/meizu/M6T/proprietary/lib/libimsma.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimsma.so \
    device/meizu/M6T/proprietary/lib/libimsma_rtp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimsma_rtp.so \
    device/meizu/M6T/proprietary/lib/libimsma_socketwrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libimsma_socketwrapper.so \
    device/meizu/M6T/proprietary/lib/libion_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libion_mtk.so \
    device/meizu/M6T/proprietary/lib/libjni_lomoeffect.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjni_lomoeffect.so \
    device/meizu/M6T/proprietary/lib/libjni_pq.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjni_pq.so \
    device/meizu/M6T/proprietary/lib/liblic_divx.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblic_divx.so \
    device/meizu/M6T/proprietary/lib/liblic_s263.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblic_s263.so \
    device/meizu/M6T/proprietary/lib/libm4u.so:$(TARGET_COPY_OUT_VENDOR)/lib/libm4u.so \
    device/meizu/M6T/proprietary/lib/libmal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmal.so \
    device/meizu/M6T/proprietary/lib/libmal_datamngr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmal_datamngr.so \
    device/meizu/M6T/proprietary/lib/libmal_epdga.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmal_epdga.so \
    device/meizu/M6T/proprietary/lib/libmal_imsmngr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmal_imsmngr.so \
    device/meizu/M6T/proprietary/lib/libmal_mdmngr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmal_mdmngr.so \
    device/meizu/M6T/proprietary/lib/libmal_nwmngr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmal_nwmngr.so \
    device/meizu/M6T/proprietary/lib/libmal_rds.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmal_rds.so \
    device/meizu/M6T/proprietary/lib/libmal_rilproxy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmal_rilproxy.so \
    device/meizu/M6T/proprietary/lib/libmal_simmngr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmal_simmngr.so \
    device/meizu/M6T/proprietary/lib/libmatv_cust.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmatv_cust.so \
    device/meizu/M6T/proprietary/lib/libmdfx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdfx.so \
    device/meizu/M6T/proprietary/lib/libmdloggerrecycle.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdloggerrecycle.so \
    device/meizu/M6T/proprietary/lib/libmeizucamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmeizucamera.so \
    device/meizu/M6T/proprietary/lib/libmemoryDumpEncoder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmemoryDumpEncoder.so \
    device/meizu/M6T/proprietary/lib/libmemorydumper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmemorydumper.so \
    device/meizu/M6T/proprietary/lib/libmhalImageCodec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmhalImageCodec.so \
    device/meizu/M6T/proprietary/lib/libminiui.so:$(TARGET_COPY_OUT_VENDOR)/lib/libminiui.so \
    device/meizu/M6T/proprietary/lib/libmjcFakeEngine.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmjcFakeEngine.so \
    device/meizu/M6T/proprietary/lib/libmmprofile.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmprofile.so \
    device/meizu/M6T/proprietary/lib/libmmprofile_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmprofile_jni.so \
    device/meizu/M6T/proprietary/lib/libmmsdkservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmsdkservice.so \
    device/meizu/M6T/proprietary/lib/libmnl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmnl.so \
    device/meizu/M6T/proprietary/lib/libmp4enc_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmp4enc_sa.ca7.so \
    device/meizu/M6T/proprietary/lib/libmp4enc_xa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmp4enc_xa.ca7.so \
    device/meizu/M6T/proprietary/lib/libmpbase.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmpbase.so \
    device/meizu/M6T/proprietary/lib/libmpe.driver.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmpe.driver.so \
    device/meizu/M6T/proprietary/lib/libmpe.sensorlistener.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmpe.sensorlistener.so \
    device/meizu/M6T/proprietary/lib/libmrdump.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmrdump.so \
    device/meizu/M6T/proprietary/lib/libmsbc_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmsbc_mtk.so \
    device/meizu/M6T/proprietary/lib/libmtcloader.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtcloader.so \
    device/meizu/M6T/proprietary/lib/libmtee.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtee.so \
    device/meizu/M6T/proprietary/lib/libmtk_drvb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtk_drvb.so \
    device/meizu/M6T/proprietary/lib/libmtk_mmutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtk_mmutils.so \
    device/meizu/M6T/proprietary/lib/libmtk_vt_service.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtk_vt_service.so \
    device/meizu/M6T/proprietary/lib/libmtk_vt_swip.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtk_vt_swip.so \
    device/meizu/M6T/proprietary/lib/libmtk_vt_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtk_vt_utils.so \
    device/meizu/M6T/proprietary/lib/libmtk_vt_wrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtk_vt_wrapper.so \
    device/meizu/M6T/proprietary/lib/libmtkcam_fwkutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkcam_fwkutils.so \
    device/meizu/M6T/proprietary/lib/libmtkjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkjpeg.so \
    device/meizu/M6T/proprietary/lib/libmtklimiter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtklimiter.so \
    device/meizu/M6T/proprietary/lib/libmtkplayer.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkplayer.so \
    device/meizu/M6T/proprietary/lib/libmtkshifter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmtkshifter.so \
    device/meizu/M6T/proprietary/lib/libn3d3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libn3d3a.so \
    device/meizu/M6T/proprietary/lib/libnativecheck-jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnativecheck-jni.so \
    device/meizu/M6T/proprietary/lib/libnvram.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram.so \
    device/meizu/M6T/proprietary/lib/libnvram_daemon_callback.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram_daemon_callback.so \
    device/meizu/M6T/proprietary/lib/libnvram_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram_platform.so \
    device/meizu/M6T/proprietary/lib/libnvram_sec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvram_sec.so \
    device/meizu/M6T/proprietary/lib/libnvramagentclient.so:$(TARGET_COPY_OUT_VENDOR)/lib/libnvramagentclient.so \
    device/meizu/M6T/proprietary/lib/libperfservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libperfservice.so \
    device/meizu/M6T/proprietary/lib/libperfservicenative.so:$(TARGET_COPY_OUT_VENDOR)/lib/libperfservicenative.so \
    device/meizu/M6T/proprietary/lib/libphoto_timestamp.so:$(TARGET_COPY_OUT_VENDOR)/lib/libphoto_timestamp.so \
    device/meizu/M6T/proprietary/lib/libpq_cust.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpq_cust.so \
    device/meizu/M6T/proprietary/lib/libpq_prot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpq_prot.so \
    device/meizu/M6T/proprietary/lib/libpqservice.so:$(TARGET_COPY_OUT_VENDOR)/lib/libpqservice.so \
    device/meizu/M6T/proprietary/lib/libprogrambinary.so:$(TARGET_COPY_OUT_VENDOR)/lib/libprogrambinary.so \
    device/meizu/M6T/proprietary/lib/libratconfig.so:$(TARGET_COPY_OUT_VENDOR)/lib/libratconfig.so \
    device/meizu/M6T/proprietary/lib/librilmtk.so:$(TARGET_COPY_OUT_VENDOR)/lib/librilmtk.so \
    device/meizu/M6T/proprietary/lib/librilmtkmd2.so:$(TARGET_COPY_OUT_VENDOR)/lib/librilmtkmd2.so \
    device/meizu/M6T/proprietary/lib/librilproxy.so:$(TARGET_COPY_OUT_VENDOR)/lib/librilproxy.so \
    device/meizu/M6T/proprietary/lib/librilproxyutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/librilproxyutils.so \
    device/meizu/M6T/proprietary/lib/librpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/librpc.so \
    device/meizu/M6T/proprietary/lib/librpcril.so:$(TARGET_COPY_OUT_VENDOR)/lib/librpcril.so \
    device/meizu/M6T/proprietary/lib/librrc.so:$(TARGET_COPY_OUT_VENDOR)/lib/librrc.so \
    device/meizu/M6T/proprietary/lib/libshowlogo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libshowlogo.so \
    device/meizu/M6T/proprietary/lib/libsimaka.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsimaka.so \
    device/meizu/M6T/proprietary/lib/libsink.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsink.so \
    device/meizu/M6T/proprietary/lib/libsource.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsource.so \
    device/meizu/M6T/proprietary/lib/libspeech_enh_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libspeech_enh_lib.so \
    device/meizu/M6T/proprietary/lib/libssl-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib/libssl-ss.so \
    device/meizu/M6T/proprietary/lib/libstagefrighthw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstagefrighthw.so \
    device/meizu/M6T/proprietary/lib/libstrongswan.so:$(TARGET_COPY_OUT_VENDOR)/lib/libstrongswan.so \
    device/meizu/M6T/proprietary/lib/libsysenv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libsysenv.so \
    device/meizu/M6T/proprietary/lib/libteeclientjni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libteeclientjni.so \
    device/meizu/M6T/proprietary/lib/libthermalalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libthermalalgo.so \
    device/meizu/M6T/proprietary/lib/libtimestretch.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtimestretch.so \
    device/meizu/M6T/proprietary/lib/libtouchfilter.so:$(TARGET_COPY_OUT_VENDOR)/lib/libtouchfilter.so \
    device/meizu/M6T/proprietary/lib/libudf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libudf.so \
    device/meizu/M6T/proprietary/lib/libui_ext.so:$(TARGET_COPY_OUT_VENDOR)/lib/libui_ext.so \
    device/meizu/M6T/proprietary/lib/libvc1dec_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvc1dec_sa.ca7.so \
    device/meizu/M6T/proprietary/lib/libvcodec_cap.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcodec_cap.so \
    device/meizu/M6T/proprietary/lib/libvcodec_oal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcodec_oal.so \
    device/meizu/M6T/proprietary/lib/libvcodec_utility.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcodec_utility.so \
    device/meizu/M6T/proprietary/lib/libvcodecdrv.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvcodecdrv.so \
    device/meizu/M6T/proprietary/lib/libvfb_render.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvfb_render.so \
    device/meizu/M6T/proprietary/lib/libviagpsrpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libviagpsrpc.so \
    device/meizu/M6T/proprietary/lib/libviatelecom-withuim-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/libviatelecom-withuim-ril.so \
    device/meizu/M6T/proprietary/lib/libvoicerecognition.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvoicerecognition.so \
    device/meizu/M6T/proprietary/lib/libvoicerecognition_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvoicerecognition_jni.so \
    device/meizu/M6T/proprietary/lib/libvp8dec_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvp8dec_sa.ca7.so \
    device/meizu/M6T/proprietary/lib/libvp8enc_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvp8enc_sa.ca7.so \
    device/meizu/M6T/proprietary/lib/libvp9dec_sa.ca7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvp9dec_sa.ca7.so \
    device/meizu/M6T/proprietary/lib/libvt_avsync.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvt_avsync.so \
    device/meizu/M6T/proprietary/lib/libvt_custom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvt_custom.so \
    device/meizu/M6T/proprietary/lib/libvt_socketbind.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvt_socketbind.so \
    device/meizu/M6T/proprietary/lib/libvtmal.so:$(TARGET_COPY_OUT_VENDOR)/lib/libvtmal.so \
    device/meizu/M6T/proprietary/lib/libwfo_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwfo_jni.so \
    device/meizu/M6T/proprietary/lib/libwo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libwo.so \
    device/meizu/M6T/proprietary/lib/mediadrm/libwvdrmengine.so:$(TARGET_COPY_OUT_VENDOR)/lib/mediadrm/libwvdrmengine.so \
    device/meizu/M6T/proprietary/lib/mtk-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib/mtk-ril.so \
    device/meizu/M6T/proprietary/lib/mtk-rilmd2.so:$(TARGET_COPY_OUT_VENDOR)/lib/mtk-rilmd2.so \
    device/meizu/M6T/proprietary/lib/mtk-rilproxy.so:$(TARGET_COPY_OUT_VENDOR)/lib/mtk-rilproxy.so \
    device/meizu/M6T/proprietary/lib/volte_imsm.so:$(TARGET_COPY_OUT_VENDOR)/lib/volte_imsm.so \
    device/meizu/M6T/proprietary/lib64/drm/libdrmctaplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib64/drm/libdrmctaplugin.so \
    device/meizu/M6T/proprietary/lib64/drm/libdrmmtkplugin.so:$(TARGET_COPY_OUT_VENDOR)/lib64/drm/libdrmmtkplugin.so \
    device/meizu/M6T/proprietary/lib64/egl/libGLES_mali.so:$(TARGET_COPY_OUT_VENDOR)/lib64/egl/libGLES_mali.so \
    device/meizu/M6T/proprietary/lib64/hw/audio.primary.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.primary.mt6750.so \
    device/meizu/M6T/proprietary/lib64/hw/audio.r_submix.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.r_submix.mt6750.so \
    device/meizu/M6T/proprietary/lib64/hw/audio.usb.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/audio.usb.mt6750.so \
    device/meizu/M6T/proprietary/lib64/hw/camera.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/camera.mt6750.so \
    device/meizu/M6T/proprietary/lib64/hw/fingerprint.default.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/fingerprint.default.so \
    device/meizu/M6T/proprietary/lib64/hw/gatekeeper.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gatekeeper.mt6750.so \
    device/meizu/M6T/proprietary/lib64/hw/gps.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gps.mt6750.so \
    device/meizu/M6T/proprietary/lib64/hw/gralloc.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/gralloc.mt6750.so \
    device/meizu/M6T/proprietary/lib64/hw/hwcomposer.mt6755.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/hwcomposer.mt6755.so \
    device/meizu/M6T/proprietary/lib64/hw/keystore.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/keystore.mt6750.so \
    device/meizu/M6T/proprietary/lib64/hw/lights.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/lights.mt6750.so \
    device/meizu/M6T/proprietary/lib64/hw/memtrack.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/memtrack.mt6750.so \
    device/meizu/M6T/proprietary/lib64/hw/sensors.mt6750.so:$(TARGET_COPY_OUT_VENDOR)/lib64/hw/sensors.mt6750.so \
    device/meizu/M6T/proprietary/lib64/lib3a.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib3a.so \
    device/meizu/M6T/proprietary/lib64/lib3a_core1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib3a_core1.so \
    device/meizu/M6T/proprietary/lib64/lib3a_core2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib3a_core2.so \
    device/meizu/M6T/proprietary/lib64/lib3a_sample.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib3a_sample.so \
    device/meizu/M6T/proprietary/lib64/libBnMtkCodec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libBnMtkCodec.so \
    device/meizu/M6T/proprietary/lib64/libDepthBokehEffect.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libDepthBokehEffect.so \
    device/meizu/M6T/proprietary/lib64/libDepthBokehEffectBase.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libDepthBokehEffectBase.so \
    device/meizu/M6T/proprietary/lib64/libJpgDecPipe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libJpgDecPipe.so \
    device/meizu/M6T/proprietary/lib64/libJpgEncPipe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libJpgEncPipe.so \
    device/meizu/M6T/proprietary/lib64/libMiraVision_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libMiraVision_jni.so \
    device/meizu/M6T/proprietary/lib64/libMtkOmxCore.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libMtkOmxCore.so \
    device/meizu/M6T/proprietary/lib64/libMtkVideoSpeedEffect.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libMtkVideoSpeedEffect.so \
    device/meizu/M6T/proprietary/lib64/libOpenCL.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOpenCL.so \
    device/meizu/M6T/proprietary/lib64/libOpenCLIcd.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libOpenCLIcd.so \
    device/meizu/M6T/proprietary/lib64/libPQDCjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libPQDCjni.so \
    device/meizu/M6T/proprietary/lib64/libPQjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libPQjni.so \
    device/meizu/M6T/proprietary/lib64/libRSDriver_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libRSDriver_mtk.so \
    device/meizu/M6T/proprietary/lib64/libSonyIMX230PdafLibrary.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libSonyIMX230PdafLibrary.so \
    device/meizu/M6T/proprietary/lib64/libSwJpgCodec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libSwJpgCodec.so \
    device/meizu/M6T/proprietary/lib64/libaal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaal.so \
    device/meizu/M6T/proprietary/lib64/libaal_cust.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaal_cust.so \
    device/meizu/M6T/proprietary/lib64/libacdk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libacdk.so \
    device/meizu/M6T/proprietary/lib64/libaed.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaed.so \
    device/meizu/M6T/proprietary/lib64/libarcsoft_beautyshot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_beautyshot.so \
    device/meizu/M6T/proprietary/lib64/libarcsoft_high_dynamic_range.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_high_dynamic_range.so \
    device/meizu/M6T/proprietary/lib64/libarcsoft_low_light_shot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_low_light_shot.so \
    device/meizu/M6T/proprietary/lib64/libarcsoft_makeup.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libarcsoft_makeup.so \
    device/meizu/M6T/proprietary/lib64/libatvctrlservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libatvctrlservice.so \
    device/meizu/M6T/proprietary/lib64/libaudio_param_parser.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudio_param_parser.so \
    device/meizu/M6T/proprietary/lib64/libaudiocompensationfilter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiocompensationfilter.so \
    device/meizu/M6T/proprietary/lib64/libaudiocomponentengine.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiocomponentengine.so \
    device/meizu/M6T/proprietary/lib64/libaudiocustparam.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiocustparam.so \
    device/meizu/M6T/proprietary/lib64/libaudiodcrflt.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiodcrflt.so \
    device/meizu/M6T/proprietary/lib64/libaudiosetting.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiosetting.so \
    device/meizu/M6T/proprietary/lib64/libaudiotoolkit.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libaudiotoolkit.so \
    device/meizu/M6T/proprietary/lib64/libbessound_hd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbessound_hd_mtk.so \
    device/meizu/M6T/proprietary/lib64/libbinary_parse.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbinary_parse.so \
    device/meizu/M6T/proprietary/lib64/libblisrc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libblisrc.so \
    device/meizu/M6T/proprietary/lib64/libblisrc32.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libblisrc32.so \
    device/meizu/M6T/proprietary/lib64/libbluetooth_hw_test.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbluetooth_hw_test.so \
    device/meizu/M6T/proprietary/lib64/libbluetooth_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbluetooth_mtk.so \
    device/meizu/M6T/proprietary/lib64/libbluetooth_mtk_pure.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbluetooth_mtk_pure.so \
    device/meizu/M6T/proprietary/lib64/libbluetooth_relayer.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbluetooth_relayer.so \
    device/meizu/M6T/proprietary/lib64/libbluetoothem_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbluetoothem_mtk.so \
    device/meizu/M6T/proprietary/lib64/libbwc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libbwc.so \
    device/meizu/M6T/proprietary/lib64/libc2kutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libc2kutils.so \
    device/meizu/M6T/proprietary/lib64/libcam.camadapter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.camadapter.so \
    device/meizu/M6T/proprietary/lib64/libcam.camarcsoft.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.camarcsoft.so \
    device/meizu/M6T/proprietary/lib64/libcam.camnode.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.camnode.so \
    device/meizu/M6T/proprietary/lib64/libcam.camshot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.camshot.so \
    device/meizu/M6T/proprietary/lib64/libcam.client.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.client.so \
    device/meizu/M6T/proprietary/lib64/libcam.common.meizu.platform.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.common.meizu.platform.so \
    device/meizu/M6T/proprietary/lib64/libcam.common.meizu.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.common.meizu.so \
    device/meizu/M6T/proprietary/lib64/libcam.device1.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.device1.so \
    device/meizu/M6T/proprietary/lib64/libcam.device3.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.device3.so \
    device/meizu/M6T/proprietary/lib64/libcam.exif.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.exif.so \
    device/meizu/M6T/proprietary/lib64/libcam.exif.v3.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.exif.v3.so \
    device/meizu/M6T/proprietary/lib64/libcam.hal3a.v3.dng.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.hal3a.v3.dng.so \
    device/meizu/M6T/proprietary/lib64/libcam.hal3a.v3.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.hal3a.v3.so \
    device/meizu/M6T/proprietary/lib64/libcam.halsensor.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.halsensor.so \
    device/meizu/M6T/proprietary/lib64/libcam.iopipe.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.iopipe.so \
    device/meizu/M6T/proprietary/lib64/libcam.jni.lomohaljni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.jni.lomohaljni.so \
    device/meizu/M6T/proprietary/lib64/libcam.metadata.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.metadata.so \
    device/meizu/M6T/proprietary/lib64/libcam.metadataprovider.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.metadataprovider.so \
    device/meizu/M6T/proprietary/lib64/libcam.paramsmgr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.paramsmgr.so \
    device/meizu/M6T/proprietary/lib64/libcam.utils.cpuctrl.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.utils.cpuctrl.so \
    device/meizu/M6T/proprietary/lib64/libcam.utils.sensorlistener.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.utils.sensorlistener.so \
    device/meizu/M6T/proprietary/lib64/libcam.utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam.utils.so \
    device/meizu/M6T/proprietary/lib64/libcam1_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam1_utils.so \
    device/meizu/M6T/proprietary/lib64/libcam3_app.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam3_app.so \
    device/meizu/M6T/proprietary/lib64/libcam3_hwnode.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam3_hwnode.so \
    device/meizu/M6T/proprietary/lib64/libcam3_hwpipeline.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam3_hwpipeline.so \
    device/meizu/M6T/proprietary/lib64/libcam3_pipeline.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam3_pipeline.so \
    device/meizu/M6T/proprietary/lib64/libcam3_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam3_utils.so \
    device/meizu/M6T/proprietary/lib64/libcam_hwutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam_hwutils.so \
    device/meizu/M6T/proprietary/lib64/libcam_mmp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam_mmp.so \
    device/meizu/M6T/proprietary/lib64/libcam_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam_platform.so \
    device/meizu/M6T/proprietary/lib64/libcam_utils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcam_utils.so \
    device/meizu/M6T/proprietary/lib64/libcamalgo.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcamalgo.so \
    device/meizu/M6T/proprietary/lib64/libcamdrv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcamdrv.so \
    device/meizu/M6T/proprietary/lib64/libcamera_bokehutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcamera_bokehutils.so \
    device/meizu/M6T/proprietary/lib64/libcameracustom.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcameracustom.so \
    device/meizu/M6T/proprietary/lib64/libccci_util.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libccci_util.so \
    device/meizu/M6T/proprietary/lib64/libcharon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcharon.so \
    device/meizu/M6T/proprietary/lib64/libcomutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcomutils.so \
    device/meizu/M6T/proprietary/lib64/libcrypto-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcrypto-ss.so \
    device/meizu/M6T/proprietary/lib64/libcurl-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcurl-ss.so \
    device/meizu/M6T/proprietary/lib64/libcustom_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcustom_jni.so \
    device/meizu/M6T/proprietary/lib64/libcustom_nvram.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcustom_nvram.so \
    device/meizu/M6T/proprietary/lib64/libcustom_prop.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcustom_prop.so \
    device/meizu/M6T/proprietary/lib64/libcvsd_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libcvsd_mtk.so \
    device/meizu/M6T/proprietary/lib64/libdirect-coredump.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdirect-coredump.so \
    device/meizu/M6T/proprietary/lib64/libdngop.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdngop.so \
    device/meizu/M6T/proprietary/lib64/libdpframework.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdpframework.so \
    device/meizu/M6T/proprietary/lib64/libdrmmtkutil.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmmtkutil.so \
    device/meizu/M6T/proprietary/lib64/libdrmmtkwhitelist.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libdrmmtkwhitelist.so \
    device/meizu/M6T/proprietary/lib64/libeffect.facebeautypp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libeffect.facebeautypp.so \
    device/meizu/M6T/proprietary/lib64/libeffecthal.JPG.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libeffecthal.JPG.so \
    device/meizu/M6T/proprietary/lib64/libeffecthal.base.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libeffecthal.base.so \
    device/meizu/M6T/proprietary/lib64/libem_audio_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libem_audio_jni.so \
    device/meizu/M6T/proprietary/lib64/libem_bt_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libem_bt_jni.so \
    device/meizu/M6T/proprietary/lib64/libem_gpio_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libem_gpio_jni.so \
    device/meizu/M6T/proprietary/lib64/libem_lte_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libem_lte_jni.so \
    device/meizu/M6T/proprietary/lib64/libem_mbim_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libem_mbim_jni.so \
    device/meizu/M6T/proprietary/lib64/libem_modem_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libem_modem_jni.so \
    device/meizu/M6T/proprietary/lib64/libem_sensor_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libem_sensor_jni.so \
    device/meizu/M6T/proprietary/lib64/libem_support_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libem_support_jni.so \
    device/meizu/M6T/proprietary/lib64/libem_usb_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libem_usb_jni.so \
    device/meizu/M6T/proprietary/lib64/libem_wifi_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libem_wifi_jni.so \
    device/meizu/M6T/proprietary/lib64/libfeatureio.cfb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfeatureio.cfb.so \
    device/meizu/M6T/proprietary/lib64/libfeatureio.featurefactory.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfeatureio.featurefactory.so \
    device/meizu/M6T/proprietary/lib64/libfeatureio.jpg.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfeatureio.jpg.so \
    device/meizu/M6T/proprietary/lib64/libfeatureio.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfeatureio.so \
    device/meizu/M6T/proprietary/lib64/libfeatureiodrv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfeatureiodrv.so \
    device/meizu/M6T/proprietary/lib64/libfile_op.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfile_op.so \
    device/meizu/M6T/proprietary/lib64/libfilter_effects.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfilter_effects.so \
    device/meizu/M6T/proprietary/lib64/libfmjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfmjni.so \
    device/meizu/M6T/proprietary/lib64/libgas.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgas.so \
    device/meizu/M6T/proprietary/lib64/libged.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libged.so \
    device/meizu/M6T/proprietary/lib64/libgf_ca.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgf_ca.so \
    device/meizu/M6T/proprietary/lib64/libgf_hal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgf_hal.so \
    device/meizu/M6T/proprietary/lib64/libgoodixfingerprintd_binder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgoodixfingerprintd_binder.so \
    device/meizu/M6T/proprietary/lib64/libgpu_aux.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgpu_aux.so \
    device/meizu/M6T/proprietary/lib64/libgralloc_extra.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgralloc_extra.so \
    device/meizu/M6T/proprietary/lib64/libgui_ext.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libgui_ext.so \
    device/meizu/M6T/proprietary/lib64/libhdrproc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhdrproc.so \
    device/meizu/M6T/proprietary/lib64/libhwm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhwm.so \
    device/meizu/M6T/proprietary/lib64/libhydra.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libhydra.so \
    device/meizu/M6T/proprietary/lib64/libifaa_daemon.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libifaa_daemon.so \
    device/meizu/M6T/proprietary/lib64/libimage_type_recognition.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimage_type_recognition.so \
    device/meizu/M6T/proprietary/lib64/libimageio.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimageio.so \
    device/meizu/M6T/proprietary/lib64/libimageio_plat_drv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimageio_plat_drv.so \
    device/meizu/M6T/proprietary/lib64/libimsg_log.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimsg_log.so \
    device/meizu/M6T/proprietary/lib64/libimsma.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimsma.so \
    device/meizu/M6T/proprietary/lib64/libimsma_rtp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimsma_rtp.so \
    device/meizu/M6T/proprietary/lib64/libimsma_socketwrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libimsma_socketwrapper.so \
    device/meizu/M6T/proprietary/lib64/libion_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libion_mtk.so \
    device/meizu/M6T/proprietary/lib64/libipsec_ims_shr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libipsec_ims_shr.so \
    device/meizu/M6T/proprietary/lib64/libjni_lomoeffect.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libjni_lomoeffect.so \
    device/meizu/M6T/proprietary/lib64/libjni_pq.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libjni_pq.so \
    device/meizu/M6T/proprietary/lib64/libm4u.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libm4u.so \
    device/meizu/M6T/proprietary/lib64/libmal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmal.so \
    device/meizu/M6T/proprietary/lib64/libmal_datamngr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmal_datamngr.so \
    device/meizu/M6T/proprietary/lib64/libmal_epdga.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmal_epdga.so \
    device/meizu/M6T/proprietary/lib64/libmal_imsmngr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmal_imsmngr.so \
    device/meizu/M6T/proprietary/lib64/libmal_mdmngr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmal_mdmngr.so \
    device/meizu/M6T/proprietary/lib64/libmal_nwmngr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmal_nwmngr.so \
    device/meizu/M6T/proprietary/lib64/libmal_rds.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmal_rds.so \
    device/meizu/M6T/proprietary/lib64/libmal_rilproxy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmal_rilproxy.so \
    device/meizu/M6T/proprietary/lib64/libmal_simmngr.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmal_simmngr.so \
    device/meizu/M6T/proprietary/lib64/libmatv_cust.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmatv_cust.so \
    device/meizu/M6T/proprietary/lib64/libmdfx.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdfx.so \
    device/meizu/M6T/proprietary/lib64/libmdloggerrecycle.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmdloggerrecycle.so \
    device/meizu/M6T/proprietary/lib64/libmeizucamera.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmeizucamera.so \
    device/meizu/M6T/proprietary/lib64/libmemoryDumpEncoder.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmemoryDumpEncoder.so \
    device/meizu/M6T/proprietary/lib64/libmemorydumper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmemorydumper.so \
    device/meizu/M6T/proprietary/lib64/libmhalImageCodec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmhalImageCodec.so \
    device/meizu/M6T/proprietary/lib64/libminiui.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libminiui.so \
    device/meizu/M6T/proprietary/lib64/libmmprofile.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmprofile.so \
    device/meizu/M6T/proprietary/lib64/libmmprofile_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmmprofile_jni.so \
    device/meizu/M6T/proprietary/lib64/libmpbase.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmpbase.so \
    device/meizu/M6T/proprietary/lib64/libmrdump.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmrdump.so \
    device/meizu/M6T/proprietary/lib64/libmsbc_mtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmsbc_mtk.so \
    device/meizu/M6T/proprietary/lib64/libmtee.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtee.so \
    device/meizu/M6T/proprietary/lib64/libmtk_drvb.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtk_drvb.so \
    device/meizu/M6T/proprietary/lib64/libmtk_mmutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtk_mmutils.so \
    device/meizu/M6T/proprietary/lib64/libmtk_vt_wrapper.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtk_vt_wrapper.so \
    device/meizu/M6T/proprietary/lib64/libmtkcam_fwkutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtkcam_fwkutils.so \
    device/meizu/M6T/proprietary/lib64/libmtkjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtkjpeg.so \
    device/meizu/M6T/proprietary/lib64/libmtklimiter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtklimiter.so \
    device/meizu/M6T/proprietary/lib64/libmtkplayer.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtkplayer.so \
    device/meizu/M6T/proprietary/lib64/libmtkshifter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libmtkshifter.so \
    device/meizu/M6T/proprietary/lib64/libn3d3a.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libn3d3a.so \
    device/meizu/M6T/proprietary/lib64/libnativecheck-jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnativecheck-jni.so \
    device/meizu/M6T/proprietary/lib64/libnvram.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvram.so \
    device/meizu/M6T/proprietary/lib64/libnvram_daemon_callback.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvram_daemon_callback.so \
    device/meizu/M6T/proprietary/lib64/libnvram_platform.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvram_platform.so \
    device/meizu/M6T/proprietary/lib64/libnvram_sec.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvram_sec.so \
    device/meizu/M6T/proprietary/lib64/libnvramagentclient.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libnvramagentclient.so \
    device/meizu/M6T/proprietary/lib64/libpcre.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpcre.so \
    device/meizu/M6T/proprietary/lib64/libperfservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libperfservice.so \
    device/meizu/M6T/proprietary/lib64/libperfservicenative.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libperfservicenative.so \
    device/meizu/M6T/proprietary/lib64/libphoto_timestamp.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libphoto_timestamp.so \
    device/meizu/M6T/proprietary/lib64/libpq_cust.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpq_cust.so \
    device/meizu/M6T/proprietary/lib64/libpq_prot.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpq_prot.so \
    device/meizu/M6T/proprietary/lib64/libpqservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libpqservice.so \
    device/meizu/M6T/proprietary/lib64/libprogrambinary.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libprogrambinary.so \
    device/meizu/M6T/proprietary/lib64/libratconfig.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libratconfig.so \
    device/meizu/M6T/proprietary/lib64/librilmtk.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librilmtk.so \
    device/meizu/M6T/proprietary/lib64/librilmtkmd2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librilmtkmd2.so \
    device/meizu/M6T/proprietary/lib64/librilproxy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librilproxy.so \
    device/meizu/M6T/proprietary/lib64/librilproxyutils.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librilproxyutils.so \
    device/meizu/M6T/proprietary/lib64/librrc.so:$(TARGET_COPY_OUT_VENDOR)/lib64/librrc.so \
    device/meizu/M6T/proprietary/lib64/libsimaka.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsimaka.so \
    device/meizu/M6T/proprietary/lib64/libsink.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsink.so \
    device/meizu/M6T/proprietary/lib64/libsource.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsource.so \
    device/meizu/M6T/proprietary/lib64/libspeech_enh_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libspeech_enh_lib.so \
    device/meizu/M6T/proprietary/lib64/libssl-ss.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libssl-ss.so \
    device/meizu/M6T/proprietary/lib64/libstagefrighthw.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstagefrighthw.so \
    device/meizu/M6T/proprietary/lib64/libstrongswan.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libstrongswan.so \
    device/meizu/M6T/proprietary/lib64/libsysenv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libsysenv.so \
    device/meizu/M6T/proprietary/lib64/libteeclientjni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libteeclientjni.so \
    device/meizu/M6T/proprietary/lib64/libterservice.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libterservice.so \
    device/meizu/M6T/proprietary/lib64/libtiff.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtiff.so \
    device/meizu/M6T/proprietary/lib64/libtiff_directory.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtiff_directory.so \
    device/meizu/M6T/proprietary/lib64/libtimestretch.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtimestretch.so \
    device/meizu/M6T/proprietary/lib64/libtouchfilter.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libtouchfilter.so \
    device/meizu/M6T/proprietary/lib64/libudf.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libudf.so \
    device/meizu/M6T/proprietary/lib64/libui_ext.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libui_ext.so \
    device/meizu/M6T/proprietary/lib64/libvcodec_cap.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvcodec_cap.so \
    device/meizu/M6T/proprietary/lib64/libvcodec_oal.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvcodec_oal.so \
    device/meizu/M6T/proprietary/lib64/libvcodec_utility.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvcodec_utility.so \
    device/meizu/M6T/proprietary/lib64/libvcodecdrv.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvcodecdrv.so \
    device/meizu/M6T/proprietary/lib64/libvfb_render.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvfb_render.so \
    device/meizu/M6T/proprietary/lib64/libvt_avsync.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libvt_avsync.so \
    device/meizu/M6T/proprietary/lib64/libwapi.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwapi.so \
    device/meizu/M6T/proprietary/lib64/libwfo_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwfo_jni.so \
    device/meizu/M6T/proprietary/lib64/libwo.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libwo.so \
    device/meizu/M6T/proprietary/lib64/mtk-ril.so:$(TARGET_COPY_OUT_VENDOR)/lib64/mtk-ril.so \
    device/meizu/M6T/proprietary/lib64/mtk-rilmd2.so:$(TARGET_COPY_OUT_VENDOR)/lib64/mtk-rilmd2.so \
    device/meizu/M6T/proprietary/lib64/mtk-rilproxy.so:$(TARGET_COPY_OUT_VENDOR)/lib64/mtk-rilproxy.so \
    device/meizu/M6T/proprietary/lib64/volte_imsm.so:$(TARGET_COPY_OUT_VENDOR)/lib64/volte_imsm.so \
    device/meizu/M6T/proprietary/thh/alipayapp:$(TARGET_COPY_OUT_VENDOR)/thh/alipayapp \
    device/meizu/M6T/proprietary/thh/soter.raw:$(TARGET_COPY_OUT_VENDOR)/thh/soter.raw
